/*global systemDictionary:true */
"use strict";

systemDictionary = {
	"stiebel-isg adapter settings": {
		"en": "Adapter settings for stiebel-isg",
		"de": "Adaptereinstellungen für Stiebel-ISG",
		"ru": "Настройки адаптера для stiebel-isg",
		"pt": "Configurações do adaptador para stiebel-isg",
		"nl": "Adapterinstellingen voor stiebel-isg",
		"fr": "Paramètres d'adaptateur pour stiebel-isg",
		"it": "Impostazioni dell'adattatore per stiebel-isg",
		"es": "Ajustes del adaptador para stiebel-isg",
		"pl": "Ustawienia adaptera dla stiebel-isg",
		"zh-cn": "stiebel-isg的适配器设置"
	},
	"IP address or domain of the isg": {
		"en": "ip address or domain of the Internet Service Gateway",
		"de": "IP-Adresse oder Domäne des Internet Service Gateway",
		"ru": "IP-адрес или домен Интернет-шлюза",
		"pt": "endereço ip ou domínio do gateway de serviço de Internet",
		"nl": "ip-adres of domein van de Internet Service Gateway",
		"fr": "adresse IP ou domaine de la passerelle de service Internet",
		"it": "indirizzo IP o dominio dell'Internet Service Gateway",
		"es": "dirección IP o dominio de Internet Service Gateway",
		"pl": "adres IP lub domena bramy usług internetowych",
		"zh-cn": "Internet服务网关的IP地址或域"
	},
	"username for the isg":  {
		"en": "username of the Internet Service Gateway",
		"de": "Benutzername des Internet Service Gateway",
		"ru": "имя пользователя Интернет-шлюза",
		"pt": "nome de usuário do gateway de serviço de Internet",
		"nl": "gebruikersnaam van de Internet Service Gateway",
		"fr": "nom d'utilisateur de la passerelle de service Internet",
		"it": "nome utente dell'Internet Service Gateway",
		"es": "nombre de usuario de Internet Service Gateway",
		"pl": "nazwa użytkownika bramy usług internetowych",
		"zh-cn": "Internet服务网关的用户名"
	},
	"password for the isg":  {
		"en": "password of the Internet Service Gateway",
		"de": "Passwort des Internet Service Gateway",
		"ru": "пароль интернет-шлюза",
		"pt": "senha do gateway de serviço de Internet",
		"nl": "wachtwoord van de Internet Service Gateway",
		"fr": "mot de passe de la passerelle de service Internet",
		"it": "password di Internet Service Gateway",
		"es": "contraseña de Internet Service Gateway",
		"pl": "hasło do bramy usług internetowych",
		"zh-cn": "Internet服务网关的密码"
	},
	"IP address":  {
		"en": "ip address",
		"de": "IP Adresse",
		"ru": "айпи адрес",
		"pt": "endereço de IP",
		"nl": "IP adres",
		"fr": "adresse IP",
		"it": "indirizzo IP",
		"es": "dirección IP",
		"pl": "adres IP",
		"zh-cn": "IP地址"
	},
	"username":  {
		"en": "username of the webinterface",
		"de": "Benutzername der Weboberfläche",
		"ru": "имя пользователя веб-интерфейса",
		"pt": "nome de usuário da interface da web",
		"nl": "gebruikersnaam van de webinterface",
		"fr": "nom d'utilisateur de l'interface web",
		"it": "nome utente dell'interfaccia web",
		"es": "nombre de usuario de la interfaz web",
		"pl": "nazwa użytkownika interfejsu internetowego",
		"zh-cn": "Web界面的用户名"
	},
	"password":  {
		"en": "password of the webinterface",
		"de": "Passwort der Weboberfläche",
		"ru": "пароль веб-интерфейса",
		"pt": "senha da interface web",
		"nl": "wachtwoord van de webinterface",
		"fr": "mot de passe de l'interface web",
		"it": "password dell'interfaccia web",
		"es": "contraseña de la interfaz web",
		"pl": "hasło do interfejsu internetowego",
		"zh-cn": "Web界面的密码"
	},
	"intervall for values to pull":  {
		"en": "interval for collecting new values ​​from the ISG",
		"de": "Intervall zum Abholen neuer Werte des ISG",
		"ru": "интервал для сбора новых значений из ISG",
		"pt": "intervalo para coleta de novos valores do ISG",
		"nl": "interval voor het verzamelen van nieuwe waarden van de ISG",
		"fr": "intervalle de collecte de nouvelles valeurs de l'ISG",
		"it": "intervallo per la raccolta di nuovi valori dall'ISG",
		"es": "intervalo para recopilar nuevos valores del ISG",
		"pl": "interwał zbierania nowych wartości z ISG",
		"zh-cn": "从ISG收集新值的间隔"
	},
	"intervall for commands to pull":  {
		"en": "Interval for collecting new setting values ​​from the ISG (changes are less common)",
		"de": "Intervall zum Sammeln neuer Einstellwerte des ISG (Änderungen sind seltener)",
		"ru": "Интервал для сбора новых значений настроек из ISG (изменения встречаются реже)",
		"pt": "Intervalo para coletar novos valores de configuração do ISG (as alterações são menos comuns)",
		"nl": "Interval voor het verzamelen van nieuwe instellingswaarden van de ISG (wijzigingen komen minder vaak voor)",
		"fr": "Intervalle de collecte des nouvelles valeurs de réglage de l'ISG (les changements sont moins courants)",
		"it": "Intervallo per la raccolta di nuovi valori di impostazione dall'ISG (le modifiche sono meno comuni)",
		"es": "Intervalo para recopilar nuevos valores de configuración del ISG (los cambios son menos comunes)",
		"pl": "Częstotliwość zbierania nowych wartości ustawień z ISG (zmiany są mniej powszechne)",
		"zh-cn": "从ISG收集新设置值的时间间隔（更改较不常见）"
	},
	"isg password":  {
		"en": "password ISG",
		"de": "Passwort ISG",
		"ru": "пароль ISG",
		"pt": "senha ISG",
		"nl": "wachtwoord ISG",
		"fr": "mot de passe ISG",
		"it": "password ISG",
		"es": "contraseña ISG",
		"pl": "hasło ISG",
		"zh-cn": "密码ISG"
	},
	"settings":  {
		"en": "settings",
		"de": "Einstellungen",
		"ru": "настройки",
		"pt": "definições",
		"nl": "instellingen",
		"fr": "Les paramètres",
		"it": "impostazioni",
		"es": "ajustes",
		"pl": "ustawienia",
		"zh-cn": "设定"
	},
	"yes":  {
		"en": "yes",
		"de": "Ja",
		"ru": "да",
		"pt": "sim",
		"nl": "Ja",
		"fr": "Oui",
		"it": "sì",
		"es": "sí",
		"pl": "tak",
		"zh-cn": "是的"
	},
	"no":  {
		"en": "no",
		"de": "Nein",
		"ru": "нет",
		"pt": "não",
		"nl": "Nee",
		"fr": "non",
		"it": "no",
		"es": "No",
		"pl": "Nie",
		"zh-cn": "不"
	},
	"umlauts active": {
		"en": "Activate umlauts in objects. Warning: could cause problems in history-adapter.",
		"de": "Aktivieren von Umlauten in Objektennamen. Warnung: Kann Probleme im History-Adapter verursachen.",
		"ru": "Активируйте умляуты в объектах. Предупреждение: может вызвать проблемы в истории-адаптере.",
		"pt": "Ative tremas em objetos. Aviso: pode causar problemas no adaptador de histórico.",
		"nl": "Activeer umlauts in objecten. Waarschuwing: kan problemen veroorzaken in history-adapter.",
		"fr": "Activez les trémas dans les objets. Avertissement: pourrait causer des problèmes dans history-adapter.",
		"it": "Attiva dieresi negli oggetti. Attenzione: potrebbe causare problemi in history-adapter.",
		"es": "Activar diéresis en objetos. Advertencia: podría causar problemas en history-adapter.",
		"pl": "Aktywuj umlauty w obiektach. Ostrzeżenie: może powodować problemy w adapterze historii.",
		"zh-cn": "激活对象中的变音符号。警告：可能导致历史适配器出现问题。"
	},
	'ending of urls behind "/?s=" of isg-pages for settings, separated by ";"': {
		"en": "ending of urls behind \"/?s=\" of isg-pages for settings, separated by \";\"",
		"de": "Ende der URLs hinter \"/? s =\" der ISG-Seiten für Einstellungen, getrennt durch \";\"",
		"ru": "окончание URL-адресов после \"/? s =\" isg-страниц для настроек, разделенных знаком \";\"",
		"pt": "final de urls atrás de \"/? s =\" das páginas isg para configurações, separadas por \";\"",
		"nl": "einde van URL's achter \"/? s =\" van isg-pagina's voor instellingen, gescheiden door \";\"",
		"fr": "fin des URL derrière \"/? s =\" des pages isg pour les paramètres, séparés par \";\"",
		"it": "fine degli URL dietro \"/? s =\" di pagine isg per le impostazioni, separate da \";\"",
		"es": "final de las URL detrás de \"/? s =\" de isg-pages para la configuración, separadas por \";\"",
		"pl": "zakończenie adresów URL za „/? s =” stron isg dla ustawień, oddzielone znakiem „;”",
		"zh-cn": "设置的isg页的“ /？s =“之后的网址的结尾，以“;”分隔"
	},
	'ending of urls behind "/?s=" of isg-pages for values, separated by ";"': {
		"en": "ending of urls behind \"/?s=\" of isg-pages for values, separated by \";\"",
		"de": "Ende von URLs hinter \"/? s =\" der ISG-Seiten für Werte, getrennt durch \";\"",
		"ru": "окончание URL-адресов после \"/? s =\" isg-страниц для значений, разделенных знаком \";\"",
		"pt": "final de urls atrás de \"/? s =\" de isg-pages para valores, separados por \";\"",
		"nl": "einde van URL's achter \"/? s =\" van isg-pagina's voor waarden, gescheiden door \";\"",
		"fr": "fin des URL derrière \"/? s =\" des pages isg pour les valeurs, séparées par \";\"",
		"it": "fine degli URL dietro \"/? s =\" di pagine isg per i valori, separati da \";\"",
		"es": "final de URL detrás de \"/? s =\" de isg-pages para valores, separados por \";\"",
		"pl": "zakończenie adresów URL za „/? s =” stron isg dla wartości, oddzielone znakiem „;”",
		"zh-cn": "isg页的“ /？s =“之后的网址的结尾，以“;”分隔"
	},
	'ending of urls behind "/?s=" of isg-pages for status, separated by ";"': {
		"en": "ending of urls behind \"/?s=\" of isg-pages for status, separated by \";\"",
		"de": "Ende der URLs hinter \"/? s =\" der ISG-Seiten für Status, getrennt durch \";\"",
		"ru": "окончание URL-адресов после \"/? s =\" isg-страниц для статуса, разделенных знаком \";\"",
		"pt": "fim de urls atrás de \"/? s =\" de isg-pages para status, separados por \";\"",
		"nl": "einde van URL's achter \"/? s =\" van isg-pagina's voor status, gescheiden door \";\"",
		"fr": "fin des URL derrière \"/? s =\" des pages isg pour le statut, séparées par \";\"",
		"it": "fine degli URL dietro \"/? s =\" di isg-pages per lo stato, separati da \";\"",
		"es": "final de las URL detrás de \"/? s =\" de las páginas isg para el estado, separadas por \";\"",
		"pl": "zakończenie adresów URL za „/? s =” stron isg dla statusu, oddzielone znakiem „;”",
		"zh-cn": "isg页的状态中“ /？s =“之后的网址的结尾，以“;”分隔"
	},
	'ending of urls behind "/?s=" of isg-pages for expert values, separated by ";"': {
		"en": "ending of urls behind \"/?s=\" of isg-pages for expert values, separated by \";\"",
		"de": "Ende von URLs hinter \"/? s =\" von ISG-Seiten für Expertenwerte, getrennt durch \";\"",
		"ru": "окончание URL-адресов после \"/? s =\" isg-страниц для экспертных значений, разделенных знаком \";\"",
		"pt": "fim de urls atrás de \"/? s =\" de páginas isg para valores de especialistas, separados por \";\"",
		"nl": "einde van URL's achter \"/? s =\" van isg-pagina's voor expertwaarden, gescheiden door \";\"",
		"fr": "fin des URL derrière \"/? s =\" des pages isg pour les valeurs expert, séparées par \";\"",
		"it": "fine degli URL dietro \"/? s =\" di pagine isg per i valori esperti, separati da \";\"",
		"es": "final de URL detrás de \"/? s =\" de isg-pages para valores expertos, separados por \";\"",
		"pl": "zakończenie adresów URL za „/? s =” stron isg dla wartości eksperckich, oddzielone znakiem „;”",
		"zh-cn": "专家值的isg页面的“ /？s =“之后的网址的结尾，以“;”分隔"
	},
	"ISGReboot": {
		"en": "reboot hardware",
		"de": "Hardware neu starten",
		"ru": "перезагрузить оборудование",
		"pt": "reiniciar o hardware",
		"nl": "herstart hardware",
		"fr": "redémarrer le matériel",
		"it": "riavviare l'hardware",
		"es": "reiniciar el hardware",
		"pl": "zrestartuj sprzęt",
		"zh-cn": "重新启动硬件"
	},
	"enable expert values": {
		"en": "enable expert values",
		"de": "Expertenwerte aktivieren",
		"ru": "включить экспертные значения",
		"pt": "habilitar valores especializados",
		"nl": "maak expertwaarden mogelijk",
		"fr": "activer les valeurs expertes",
		"it": "abilitare i valori degli esperti",
		"es": "habilitar valores expertos",
		"pl": "umożliwiają wartości eksperckie",
		"zh-cn": "启用专家价值观"
	},
	"intervall": {
		"en": "intervall in seconds",
		"de": "Intervall in Sekunden",
		"ru": "интервал в секундах",
		"pt": "intervall em segundos",
		"nl": "interval in seconden",
		"fr": "intervall en secondes",
		"it": "intervallo in secondi",
		"es": "Intervall en segundos",
		"pl": "interweniować w kilka sekund",
		"zh-cn": "间隔秒"
	}
};